In [1]:
import numpy as np

Obtain eigenvalues `Mdiag` and rotation matrix `U`

In [29]:
M=[[1.77733E7, 0, -2.7946*1E7], 
               [0, 6659.79, -6659.79], 
               [-2.7946E7, -6659.79, 4.39478E7]]
Mdiag,U=np.linalg.eig(M)

Check diagonalization

In [30]:
np.dot(np.dot(U.T,M),U)

array([[  6.17191802e+07,  -3.72529030e-09,  -1.30385160e-08],
       [ -3.11438408e-09,   1.90324609e+00,   2.39900905e-10],
       [ -9.46397449e-09,  -3.56067176e-10,   8.57764906e+03]])

Show rotation matrix

In [31]:
U

array([[ -5.36608134e-01,  -7.43460375e-01,  -3.99147068e-01],
       [ -9.10632226e-05,  -4.72966442e-01,   8.81080437e-01],
       [  8.43831560e-01,  -4.72831277e-01,  -2.53729938e-01]])

Reorder eigenvectors to obtain eigenvalues in right order

In [35]:
V=np.dstack((U[:,1],U[:,2],U[:,0]))[0]
V

array([[ -7.43460375e-01,  -3.99147068e-01,  -5.36608134e-01],
       [ -4.72966442e-01,   8.81080437e-01,  -9.10632226e-05],
       [ -4.72831277e-01,  -2.53729938e-01,   8.43831560e-01]])

Obtain eigenvalues in increasing order

In [36]:
np.dot(np.dot(V.T,M),V)

array([[  1.90324609e+00,   2.39900905e-10,  -3.11438408e-09],
       [ -3.56067176e-10,   8.57764906e+03,  -9.46397449e-09],
       [ -3.72529030e-09,  -1.30385160e-08,   6.17191802e+07]])

Write expected rotation matrix

In [37]:
ZZMIX=[[0.743508, -0.399058, -0.536608], 
 [0.472861, 0.881137, -0.0000910632],
 [0.472861, -0.253673, 0.843832]]

Check that `V` and `ZZMIX` are equal

In [48]:
np.testing.assert_almost_equal(np.abs(ZZMIX),np.abs(V),decimal=4)